/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppModeRouteImport } from './routes/_app/mode'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDeploymentRouteImport } from './routes/_app/deployment'
import { Route as AppBatteryRouteImport } from './routes/_app/battery'
import { Route as AppApiRouteImport } from './routes/_app/api'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppModeRoute = AppModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentRoute = AppDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => AppRoute,
} as any)
const AppBatteryRoute = AppBatteryRouteImport.update({
  id: '/battery',
  path: '/battery',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/battery': typeof AppBatteryRoute
  '/deployment': typeof AppDeploymentRoute
  '/events': typeof AppEventsRoute
  '/fleet': typeof AppFleetRoute
  '/mode': typeof AppModeRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/battery': typeof AppBatteryRoute
  '/deployment': typeof AppDeploymentRoute
  '/events': typeof AppEventsRoute
  '/fleet': typeof AppFleetRoute
  '/mode': typeof AppModeRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api': typeof AppApiRoute
  '/_app/battery': typeof AppBatteryRoute
  '/_app/deployment': typeof AppDeploymentRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/mode': typeof AppModeRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api'
    | '/battery'
    | '/deployment'
    | '/events'
    | '/fleet'
    | '/mode'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/api'
    | '/battery'
    | '/deployment'
    | '/events'
    | '/fleet'
    | '/mode'
    | '/reports'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/api'
    | '/_app/battery'
    | '/_app/deployment'
    | '/_app/events'
    | '/_app/fleet'
    | '/_app/mode'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mode': {
      id: '/_app/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof AppModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployment': {
      id: '/_app/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof AppDeploymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battery': {
      id: '/_app/battery'
      path: '/battery'
      fullPath: '/battery'
      preLoaderRoute: typeof AppBatteryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiRoute: typeof AppApiRoute
  AppBatteryRoute: typeof AppBatteryRoute
  AppDeploymentRoute: typeof AppDeploymentRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFleetRoute: typeof AppFleetRoute
  AppModeRoute: typeof AppModeRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiRoute: AppApiRoute,
  AppBatteryRoute: AppBatteryRoute,
  AppDeploymentRoute: AppDeploymentRoute,
  AppEventsRoute: AppEventsRoute,
  AppFleetRoute: AppFleetRoute,
  AppModeRoute: AppModeRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
